const programmingWords = [
  "=",
  "{",
  "}",
  "(",
  ")",
  "[",
  "]",
  "'",
  '"',
  "for",
  "true",
  "false",
  "if",
  "while",
  "&&",
  "||",
  "+",
  "-",
  "*",
  "/",
  "=",
  "%",
  "++",
  "--",
  "+=",
  "-=",
  "*=",
  "/=",
];

const htmlWords = [
  "<input>",
  '<label for="">',
  "<select>",
  "<textarea>",
  "<button>",
  "<option>",
  '<img src="" alt="">',
  "<main>",
  "<section>",
  "<article>",
  "<footer>",
  "<header>",
  "<nav>",
  "<div>",
  "<form>",
  'class=""',
  "<h1>",
  "<h2>",
  "<h3>",
  "<h4>",
  "<h5>",
  "<h6>",
  "<p>",
  "<span>",
  "<ul>",
  "<ol>",
  "<li>",
  '<a href="">',
  '<id="">',
  "<aside>",
  "<details>",
  "<figcaption>",
  "<figure>",
  "<section>",
  "<summary>",
  "<time>",
];

const cssWords = [
  "color",
  "position",
  "display",
  "background",
  "line-height",
  "text-align",
  "border",
  "font-size",
  "font-weight",
  "cursor",
  "margin",
  "min-height",
  "max-width",
  "padding",
  "margin-right",
  "margin-bottom",
  "padding-left",
  "padding-top",
  "outline",
  "overflow",
  "width",
  "height",
  "z-index",
  "visibility",
];

const jsWords = [
  "const",
  "let",
  "`",
  "this",
  "() =>",
  "function()",
  "document",
  "querySelector",
  "localStorage",
  "keycode",
  "innerHTML",
  "for (variable of iterable) {}",
  "console.log()",
];

const phpWords = [
  "<?php ?>",
  "echo",
  "$",
  "fopen",
  "fread",
  "fclose",
  "setcookie",
  "$_SESSION",
  "session_start();",
  "fwrite()",
  "public $name;",
  "protected $color;",
  "private $weight;",
];

const cSharpWords = [
  "Console.WriteLine();",
  'string name="John";',
  "public",
  "private",
  "protected",
  "abstract",
  "interface",
  "virtual",
  "try{} catch(Exception e){}",
];

const javaWords = [
  "System.out.println();",
  "public class",
  "String name",
  "int myNum",
  "char myLetter",
  "boolean myBool",
  "float myFloatNum",
  "String[] cars;",
  "static void myMethod() {}",
  "public static void main(String[] args) {}",
  "public abstract void animalSound()",
  "public String getName() {return name;}",
  "public void setName(String newName) {this.name = newName;}",
];
